name:                currycoin
version:             0.1.0.1

dependencies:
- base
- cryptohash-sha256
- bytestring
- secp256k1-haskell
- base58-bytestring
- base16
- entropy
- random
- mtl
- haskeline
- utf8-string
- containers
- ppad-ripemd160
- base58-bytestring
- binary

library:
  source-dirs: src

executables:
  currycoin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - currycoin

tests:
  currycoin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - currycoin
    - tasty
    - tasty-hunit
