# TODO: Replace `my-project` everywhere in this file with your project name.
name:                currycoin
version:             0.1.0.0

dependencies:
- base
- cryptohash-sha256
- bytestring
- secp256k1-haskell
- base58-bytestring
- entropy

library:
  source-dirs: src

executables:
  currycoin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - currycoin

tests:
  currycoin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - currycoin
    - tasty
    - tasty-hunit
